on: [push]

jobs:
  codesigner:
    runs-on: ubuntu-latest
    name: Run CodeSigner Action
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Compile Java Library
        shell: bash
        run: |
          javac ${GITHUB_WORKSPACE}/test/src/HelloWorld.java -d ${GITHUB_WORKSPACE}/build

      - name: Build Java Jar
        shell: bash
        run: |
          jar cmf ${GITHUB_WORKSPACE}/test/src/HelloWorld.mf ${GITHUB_WORKSPACE}/test/src/build/HelloWorld.jar ${GITHUB_WORKSPACE}/test/src/build/HelloWorld.class ${GITHUB_WORKSPACE}/test/src/HelloWorld.java

      - name: Build Artifacts Directory
        shell: bash
        run: |
          mkdir ${GITHUB_WORKSPACE}/artifacts

      - name: Sign Files
        uses: bayrakmustafa/actions-codesigner@develop
        with:
          command: sign
          username: ${{secrets.ES_USERNAME}}
          password: ${{secrets.ES_PASSWORD}}
          credential_id: ${{secrets.CREDENTIAL_ID}}
          totp_secret: ${{secrets.ES_TOTP_SECRET}}
          file_path: ${GITHUB_WORKSPACE}/test/src/build/HelloWorld.jar
          output_path: ${GITHUB_WORKSPACE}/artifacts
          malware_block: false
          environment_name: DEV

      - name: Upload Signed Files
        uses: actions/upload-artifact@v3
        with:
          name: HelloWorld.jar
          path: ./artifacts/HelloWorld.jar
